# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'telaExcluir.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Tela_Excluir(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(650, 450)
        MainWindow.setMinimumSize(QtCore.QSize(650, 450))
        MainWindow.setMaximumSize(QtCore.QSize(650, 450))
        MainWindow.setStyleSheet("background-color: rgb(100, 61, 135);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.txt_nomeTelaSaque = QtWidgets.QLabel(self.centralwidget)
        self.txt_nomeTelaSaque.setGeometry(QtCore.QRect(240, 40, 181, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.txt_nomeTelaSaque.setFont(font)
        self.txt_nomeTelaSaque.setStyleSheet("color: rgb(255, 85, 0);\n"
"")
        self.txt_nomeTelaSaque.setAlignment(QtCore.Qt.AlignCenter)
        self.txt_nomeTelaSaque.setObjectName("txt_nomeTelaSaque")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(120, 130, 411, 281))
        self.frame.setStyleSheet("background-color: rgba(0, 0, 0, 0.4);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.btn_excluir = QtWidgets.QPushButton(self.frame)
        self.btn_excluir.setGeometry(QtCore.QRect(170, 190, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_excluir.setFont(font)
        self.btn_excluir.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_excluir.setStyleSheet("QPushButton{\n"
"    background-color: rgb(0, 0, 0);\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius: 10px\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgb(255, 0, 0);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"")
        self.btn_excluir.setObjectName("btn_excluir")
        self.btn_voltar = QtWidgets.QPushButton(self.frame)
        self.btn_voltar.setGeometry(QtCore.QRect(180, 240, 75, 23))
        self.btn_voltar.setStyleSheet("QPushButton {\n"
"    background-color: rgb(0, 0, 0);    \n"
"    color: rgb(255, 255, 255);\n"
"    border-radius: 10px\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(255, 255, 255);\n"
"    color: rgb(255, 85, 0);\n"
"}")
        self.btn_voltar.setObjectName("btn_voltar")
        self.txt_senha = QtWidgets.QLineEdit(self.frame)
        self.txt_senha.setGeometry(QtCore.QRect(90, 80, 261, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.txt_senha.setFont(font)
        self.txt_senha.setStyleSheet("color: rgb(255, 255, 255);")
        self.txt_senha.setEchoMode(QtWidgets.QLineEdit.Password)
        self.txt_senha.setAlignment(QtCore.Qt.AlignCenter)
        self.txt_senha.setObjectName("txt_senha")
        self.txt_senhaConfirmacao = QtWidgets.QLineEdit(self.frame)
        self.txt_senhaConfirmacao.setGeometry(QtCore.QRect(90, 130, 261, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.txt_senhaConfirmacao.setFont(font)
        self.txt_senhaConfirmacao.setStyleSheet("color: rgb(255, 255, 255);")
        self.txt_senhaConfirmacao.setEchoMode(QtWidgets.QLineEdit.Password)
        self.txt_senhaConfirmacao.setAlignment(QtCore.Qt.AlignCenter)
        self.txt_senhaConfirmacao.setObjectName("txt_senhaConfirmacao")
        self.txt_nomeNumConta = QtWidgets.QLabel(self.frame)
        self.txt_nomeNumConta.setGeometry(QtCore.QRect(30, 20, 101, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.txt_nomeNumConta.setFont(font)
        self.txt_nomeNumConta.setStyleSheet("background-color: rgba(0, 0, 0, 0.4);\n"
"color: rgb(255, 255, 255);")
        self.txt_nomeNumConta.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.txt_nomeNumConta.setObjectName("txt_nomeNumConta")
        self.txt_numeroConta = QtWidgets.QLineEdit(self.frame)
        self.txt_numeroConta.setGeometry(QtCore.QRect(30, 40, 113, 20))
        self.txt_numeroConta.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.txt_numeroConta.setObjectName("txt_numeroConta")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.txt_nomeTelaSaque.setText(_translate("MainWindow", "Excluir Conta"))
        self.btn_excluir.setText(_translate("MainWindow", "Excluir"))
        self.btn_voltar.setText(_translate("MainWindow", "Voltar"))
        self.txt_senha.setPlaceholderText(_translate("MainWindow", "Senha"))
        self.txt_senhaConfirmacao.setPlaceholderText(_translate("MainWindow", "Confirme a Senha"))
        self.txt_nomeNumConta.setText(_translate("MainWindow", "Nº da conta:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Tela_Excluir()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
