# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'telaHistorico.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Tela_Historico(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(650, 480)
        MainWindow.setMinimumSize(QtCore.QSize(650, 450))
        MainWindow.setMaximumSize(QtCore.QSize(650, 480))
        MainWindow.setStyleSheet("background-color: rgb(100, 61, 135);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.txt_nomeHistorico = QtWidgets.QLabel(self.centralwidget)
        self.txt_nomeHistorico.setGeometry(QtCore.QRect(220, 10, 211, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.txt_nomeHistorico.setFont(font)
        self.txt_nomeHistorico.setStyleSheet("color: rgb(255, 85, 0);\n"
"")
        self.txt_nomeHistorico.setAlignment(QtCore.Qt.AlignCenter)
        self.txt_nomeHistorico.setObjectName("txt_nomeHistorico")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(100, 60, 451, 371))
        self.frame.setStyleSheet("background-color: rgba(0, 0, 0, 0.4);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.btn_voltar = QtWidgets.QPushButton(self.frame)
        self.btn_voltar.setGeometry(QtCore.QRect(190, 320, 81, 31))
        self.btn_voltar.setStyleSheet("QPushButton {\n"
"    \n"
"    background-color: rgb(0, 0, 0);    \n"
"    color: rgb(255, 255, 255);\n"
"    border-radius: 10px\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(255, 255, 255);\n"
"    color: rgb(255, 85, 0);\n"
"}")
        self.btn_voltar.setObjectName("btn_voltar")
        self.txt_historico = QtWidgets.QTextBrowser(self.frame)
        self.txt_historico.setGeometry(QtCore.QRect(10, 30, 431, 271))
        self.txt_historico.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.txt_historico.setObjectName("txt_historico")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.txt_nomeHistorico.setText(_translate("MainWindow", "Histórico"))
        self.btn_voltar.setText(_translate("MainWindow", "Voltar"))
        self.txt_historico.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Tela_Historico()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
