# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'telaPrincipal.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Tela_Principal(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(650, 500)
        MainWindow.setMinimumSize(QtCore.QSize(650, 500))
        MainWindow.setMaximumSize(QtCore.QSize(650, 500))
        font = QtGui.QFont()
        font.setPointSize(11)
        MainWindow.setFont(font)
        MainWindow.setStyleSheet("background-color: rgb(100, 61, 135);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(9, 260, 621, 91))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btn_sacar = QtWidgets.QPushButton(self.frame)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.btn_sacar.setFont(font)
        self.btn_sacar.setStyleSheet("QPushButton {\n"
"    background-color: rgb(255, 255, 255);\n"
"    color: rgb(255, 85, 0);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(247, 147, 0);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"")
        self.btn_sacar.setObjectName("btn_sacar")
        self.horizontalLayout.addWidget(self.btn_sacar)
        self.btn_depositar = QtWidgets.QPushButton(self.frame)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.btn_depositar.setFont(font)
        self.btn_depositar.setStyleSheet("QPushButton {\n"
"    background-color: rgb(255, 255, 255);\n"
"    color: rgb(255, 85, 0);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(247, 147, 0);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"")
        self.btn_depositar.setObjectName("btn_depositar")
        self.horizontalLayout.addWidget(self.btn_depositar)
        self.btn_transferir = QtWidgets.QPushButton(self.frame)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.btn_transferir.setFont(font)
        self.btn_transferir.setStyleSheet("QPushButton {\n"
"    background-color: rgb(255, 255, 255);\n"
"    color: rgb(255, 85, 0);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(247, 147, 0);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"")
        self.btn_transferir.setObjectName("btn_transferir")
        self.horizontalLayout.addWidget(self.btn_transferir)
        self.btn_historico = QtWidgets.QPushButton(self.frame)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.btn_historico.setFont(font)
        self.btn_historico.setStyleSheet("QPushButton {\n"
"    background-color: rgb(255, 255, 255);\n"
"    color: rgb(255, 85, 0);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(247, 147, 0);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"")
        self.btn_historico.setObjectName("btn_historico")
        self.horizontalLayout.addWidget(self.btn_historico)
        self.btn_excluirConta = QtWidgets.QPushButton(self.frame)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.btn_excluirConta.setFont(font)
        self.btn_excluirConta.setStyleSheet("QPushButton {\n"
"    background-color: rgb(255, 255, 255);\n"
"    color: rgb(255, 85, 0);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(247, 147, 0);\n"
"    color: rgb(255, 0, 0);\n"
"}\n"
"")
        self.btn_excluirConta.setObjectName("btn_excluirConta")
        self.horizontalLayout.addWidget(self.btn_excluirConta)
        self.txt_nomeSaldo = QtWidgets.QLabel(self.centralwidget)
        self.txt_nomeSaldo.setGeometry(QtCore.QRect(60, 150, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.txt_nomeSaldo.setFont(font)
        self.txt_nomeSaldo.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.txt_nomeSaldo.setObjectName("txt_nomeSaldo")
        self.txt_saldo = QtWidgets.QLineEdit(self.centralwidget)
        self.txt_saldo.setGeometry(QtCore.QRect(60, 170, 113, 20))
        self.txt_saldo.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.txt_saldo.setObjectName("txt_saldo")
        self.btn_sair = QtWidgets.QPushButton(self.centralwidget)
        self.btn_sair.setGeometry(QtCore.QRect(310, 400, 75, 23))
        self.btn_sair.setStyleSheet("QPushButton {\n"
"    background-color: rgb(255, 255, 255);\n"
"    color: rgb(255, 85, 0);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgb(255, 0, 0);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"")
        self.btn_sair.setObjectName("btn_sair")
        self.txt_nomeBanco = QtWidgets.QLabel(self.centralwidget)
        self.txt_nomeBanco.setGeometry(QtCore.QRect(220, 20, 241, 41))
        font = QtGui.QFont()
        font.setPointSize(19)
        font.setItalic(True)
        self.txt_nomeBanco.setFont(font)
        self.txt_nomeBanco.setStyleSheet("color: rgb(255, 85, 0);\n"
"")
        self.txt_nomeBanco.setScaledContents(False)
        self.txt_nomeBanco.setAlignment(QtCore.Qt.AlignCenter)
        self.txt_nomeBanco.setObjectName("txt_nomeBanco")
        self.txt_nomeUsuario = QtWidgets.QLineEdit(self.centralwidget)
        self.txt_nomeUsuario.setGeometry(QtCore.QRect(60, 120, 113, 20))
        self.txt_nomeUsuario.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.txt_nomeUsuario.setObjectName("txt_nomeUsuario")
        self.txt_usuario = QtWidgets.QLabel(self.centralwidget)
        self.txt_usuario.setGeometry(QtCore.QRect(60, 100, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.txt_usuario.setFont(font)
        self.txt_usuario.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.txt_usuario.setObjectName("txt_usuario")
        self.txt_nomeNumConta = QtWidgets.QLabel(self.centralwidget)
        self.txt_nomeNumConta.setGeometry(QtCore.QRect(510, 100, 101, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.txt_nomeNumConta.setFont(font)
        self.txt_nomeNumConta.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.txt_nomeNumConta.setObjectName("txt_nomeNumConta")
        self.txt_numeroConta = QtWidgets.QLineEdit(self.centralwidget)
        self.txt_numeroConta.setGeometry(QtCore.QRect(510, 120, 113, 20))
        self.txt_numeroConta.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.txt_numeroConta.setObjectName("txt_numeroConta")
        self.txt_limite = QtWidgets.QLineEdit(self.centralwidget)
        self.txt_limite.setGeometry(QtCore.QRect(60, 220, 113, 20))
        self.txt_limite.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.txt_limite.setText("")
        self.txt_limite.setObjectName("txt_limite")
        self.txt_nomeLimite = QtWidgets.QLabel(self.centralwidget)
        self.txt_nomeLimite.setGeometry(QtCore.QRect(60, 200, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.txt_nomeLimite.setFont(font)
        self.txt_nomeLimite.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.txt_nomeLimite.setObjectName("txt_nomeLimite")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn_sacar.setText(_translate("MainWindow", "Sacar"))
        self.btn_depositar.setText(_translate("MainWindow", "Depositar"))
        self.btn_transferir.setText(_translate("MainWindow", "Transferir"))
        self.btn_historico.setText(_translate("MainWindow", "Histórico"))
        self.btn_excluirConta.setText(_translate("MainWindow", "Excluir Conta"))
        self.txt_nomeSaldo.setText(_translate("MainWindow", "Saldo:"))
        self.btn_sair.setText(_translate("MainWindow", "Sair"))
        self.txt_nomeBanco.setText(_translate("MainWindow", "Banco Universitário"))
        self.txt_usuario.setText(_translate("MainWindow", "Usuário:"))
        self.txt_nomeNumConta.setText(_translate("MainWindow", "Nº da conta:"))
        self.txt_nomeLimite.setText(_translate("MainWindow", "Limite:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Tela_Principal()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
